[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AhoyDTU"
authors = [{name = "Lukas Pusch", email = "contact@ahoydtu.de"}]
dynamic = ["version", "description"]
